name: Development Workflow

on:
  push:
    branches: [master, main]
  pull_request:

jobs:
  test:
    timeout-minutes: 20
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-20.04, macos-10.15, windows-2019]
        node-version: [14.x, 16.x]

    runs-on: ${{ matrix.os }}

    steps:
      - name: Checkout project
        uses: actions/checkout@v2

      - name: Setup Node/Yarn
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Cache of node_modules
        uses: actions/cache@v2
        id: node-modules-cache
        with:
          path: |
            node_modules
            **/node_modules
          key: ${{ matrix.os }}-${{ matrix.node-version }}-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn --frozen-lockfile --prefer-offline

      - name: Run linters
        run: yarn lint

      - name: Run tests
        run: yarn test
